version: "3"

services:
  backend:
    build: ./apps/server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - placenext_db:/data/db 

  frontend:
    build: ./apps/web
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  placenext_db:
